/* Gerado por tools/build-icons.mjs — não edite à mão. */

/** Nome do ícone → codepoint. A fonte é subsetada por codepoint, então
 *  ligaduras (escrever "home" como texto) não funcionam mais. */
export const ICON_CODEPOINTS = {
  'account_circle': '\ue853',
  'add': '\ue145',
  'arrow_back': '\ue5c4',
  'arrow_drop_down': '\ue5c5',
  'arrow_forward': '\ue5c8',
  'avg_time': '\uf813',
  'bolt': '\uea0b',
  'bookmark_add': '\ue598',
  'calculate': '\uea5f',
  'card_membership': '\ue8f7',
  'check': '\ue5ca',
  'check_circle': '\ue86c',
  'chevron_left': '\ue408',
  'chevron_right': '\ue409',
  'close': '\ue14c',
  'compare_arrows': '\ue915',
  'dark_mode': '\ue51c',
  'database': '\uf20e',
  'delete': '\ue872',
  'directions': '\ue52e',
  'directions_car': '\ue531',
  'download': '\ue171',
  'edit': '\ue150',
  'edit_note': '\ue745',
  'electric_bolt': '\uec1c',
  'electric_car': '\ueb1c',
  'error': '\ue000',
  'ev_charger': '\ue209',
  'expand_more': '\ue5cf',
  'explore': '\ue87a',
  'favorite': '\ue87d',
  'filter_list': '\ue152',
  'format_list_bulleted': '\ue241',
  'help_outline': '\ue887',
  'history': '\ue28e',
  'home': '\ue88a',
  'horizontal_rule': '\uf108',
  'info': '\ue88e',
  'light_mode': '\ue518',
  'local_gas_station': '\ue546',
  'location_on': '\ue0c8',
  'lock': '\ue88d',
  'mail': '\ue0be',
  'manage_accounts': '\uf02e',
  'map': '\ue55b',
  'menu': '\ue5d2',
  'mic': '\ue029',
  'more_vert': '\ue5d4',
  'my_location': '\ue1b3',
  'navigation': '\ue55d',
  'notifications_active': '\ue7f7',
  'open_in_new': '\ue895',
  'person': '\ue7fd',
  'place': '\ue0c8',
  'refresh': '\ue5d5',
  'remove': '\ue15b',
  'savings': '\ue2eb',
  'schedule': '\ue192',
  'search': '\ue8b6',
  'sell': '\ue54e',
  'settings': '\ue8b8',
  'share': '\ue80d',
  'speed': '\ue9e4',
  'star': '\ue838',
  'timer': '\ue425',
  'trending_down': '\ue8e3',
  'trending_up': '\ue8e5',
  'tune': '\ue429',
  'verified': '\ue031',
  'visibility': '\ue417',
  'visibility_off': '\ue8f5',
  'warning': '\ue002',
  'wifi_off': '\ue648',
  'workspace_premium': '\ue7af',
} as const;

export type IconName = keyof typeof ICON_CODEPOINTS;
